[package]
name = "async-executor"
version = "1.4.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async executor"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-executor"
homepage = "https://github.com/smol-rs/async-executor"
documentation = "https://docs.rs/async-executor"
keywords = ["asynchronous", "executor", "single", "multi", "spawn"]
categories = ["asynchronous", "concurrency"]

[dependencies]
async-task = "4.0.0"
concurrent-queue = "1.2.2"
fastrand = "1.3.4"
futures-lite = "1.11.0"
once_cell = "1.4.1"
parking_lot = "0.11.1"
vec-arena = "1.0.0"
num_cpus = "1.13.0"
# crossbeam-utils="0.8.3"
crossbeam-queue="0.3"

[dev-dependencies]
async-oneshot="0.5"
async-channel = "1.4.1"
async-io = "1.1.9"
easy-parallel = "3.1.0"
scopeguard="1.1"
criterion = "0.3"

[profile.release]
incremental = true
debug = 2 # Set this to 1 or 2 to get more useful backtraces in debugger.
lto = 'thin'
codegen-units = 1

[[bench]]
name = "my_benchmark"
harness = false