[package]
name = "async-executor"
version = "1.4.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async executor"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-executor"
homepage = "https://github.com/stjepang/async-executor"
documentation = "https://docs.rs/async-executor"
keywords = ["asynchronous", "executor", "single", "multi", "spawn"]
categories = ["asynchronous", "concurrency"]
readme = "README.md"

[dependencies]
async-task = "4.0.0"
concurrent-queue = "1.2.2"
fastrand = "1.3.4"
futures-lite = "1.11.0"
once_cell = "1.4.1"
parking_lot = "0.11.0"
vec-arena = "1.0.0"

[dev-dependencies]
async-channel = "1.4.2"
async-io = "1.1.9"
easy-parallel = "3.1.0"
num_cpus = "1.13.0"
